// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skydiving.Infrastructure.Data;

#nullable disable

namespace Skydiving.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221217194242_message-entity2")]
    partial class messageentity2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Jump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("InstructorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<int>("JumpCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JumpStatusId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("JumpCategoryId");

                    b.HasIndex("JumpStatusId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Jumps");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.JumpCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("JumpsCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dubai, United Arab Emirates"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Interlaken, Switzerland"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sydney, Australia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "North Shore, Hawaii, USA"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pokhara, Nepal"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Other.."
                        });
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.JumpOffer", b =>
                {
                    b.Property<int>("JumpId")
                        .HasColumnType("int");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.HasKey("JumpId", "OfferId");

                    b.HasIndex("OfferId");

                    b.ToTable("JumpOffer");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.JumpStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JumpStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Declined"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Deleted"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemsDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JumpId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EquipmentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("EquipmentCategoryId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "J2 Freefly Suit",
                            Brand = "J2",
                            Quantity = 20,
                            EquipmentCategoryId = 3,
                            Description = "The J2 Free Fly Suit, with its innovative design, offers three fit options: tight, loose, or standard, tailored for any skydiver's preference. Created by three unique designers, it provides varied styles for personal expression. Its articulated design promotes free movement, ideal for skydiving's demands. Made from durable nylon, it balances strength and flexibility for optimal performance in the air.",
                            OwnerId = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            IsActive = true,
                            Price = 250.00m,
                            ImageUrl = "https://jediairwear.co.uk/wp-content/uploads/2024/01/cl-640x960.jpg"

                        },
                        new
                        {
                            Id = 2,
                            Title = "PEEKSTEEP SKYDIVING GOGGLES",
                            Brand = "PEEKSTEEP",
                            Quantity = 38,
                            EquipmentCategoryId = 2,
                            Description = "Peeksteep Skydiving Goggles take your style to the skies! Peeksteep Skydiving Goggles are a high-quality pair of skydiving goggles that also come in a variety of strap and lens colors to match your skydiving gear. Features:Large adjustable straps in a variety of colors, Anti-fog & Anti-scratch lens coating, Fits any face shape or size, Thick polycarbonate lens, UV 400 protection, Comfortable & lightweight, Ventilated lens to prevent fogging.",
                            OwnerId = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            IsActive = true,
                            Price = 20.00m,
                            ImageUrl = "https://sky-shop.eu/image/cache/catalog/Peeksteep/Goggles/peeksteep_other_01-800x800w.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "AKANDO",
                            Description = "Akando Ultimate gloves feature an L&B Ares2 pocket for improved altitude awareness. Designed for skydivers, they offer superior grip and durability, thanks to over a decade of feedback and testing. Highlights include a tackified leather palm, reinforced fingers, Kevlar stitching, a breathable back, a secure YKK velcro wrist closure, and a professional appearance.",
                            ImageUrl = "https://sky-shop.eu/image/cache/catalog/Akando/Ultimate/Akando-ultimate-lb-ares2-gloves_2-800x800.jpeg",
                            IsActive = true,
                            OwnerId = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            Price = 36.00m,
                            Quantity = 15,
                            Title = "ULTIMATE L&B ARES2 SKYDIVING GLOVES",
                            EquipmentCategoryId = 7
                        },
                        new
                        {
                            Id = 4,
                            Brand = "UPT",
                            Description = "PD Sigma Tandem Main Canopy. This canopy, made by Performance Designs exclusively for United Parachute Technologies, is the preferred choice for use with Sigma and Micro Sigma Tandem Containers.",
                            ImageUrl = "https://as2.ftcdn.net/v2/jpg/01/63/30/01/1000_F_163300195_NHBtdr1pmdOR2WhQ3TJKVn352L55IQPV.jpg",
                            IsActive = true,
                            OwnerId = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            Price = 3789.00m,
                            Quantity = 30,
                            Title = "SIGMA TANDEM MAIN CANOPY PARACHUTE",
                            EquipmentCategoryId = 6
                        },
                        new
                        {
                            Id = 5,
                            Brand = "PARASPORT",
                            Description = "Parasport's mechanical altimeter, the Aeronaut, retains its robust, cost-effective, and precise mechanism but is now redesigned. It's calibrated for up to 6,000 m (19,000 ft), featuring a temperature-adjusted aneroid capsule for consistent accuracy. The updated aluminum case, at 55 mm in diameter and 21 mm thick, is compact, with durable, water-resistant glass. It includes easily replaceable mounts with steel brackets, offering versatile orientation for either hand or wrist mounting.",
                            ImageUrl = "https://sky-shop.eu/image/cache/Parasport/Aeronaut_Tri-800x800.jpg",
                            IsActive = true,
                            OwnerId = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            Price = 209.99m,
                            Quantity = 37,
                            Title = "AERONAUT ANALOG SKYDIVING ALTIMETER",
                            EquipmentCategoryId = 5
                        },
                        new
                        {
                            Id = 6,
                            Brand = "AERODYNE",
                            Description = "The ICON Student is designed for DZ operators, instructors, and students, addressing the growing diversity and needs of student training. It offers a versatile harness and container system for Static line, IAD, AFF, or Solo freefall, meeting DZ requirements. Student jumpers value safety and comfort. The Student ICON ensures reliability, durability, and comfort, making first jumps safer and enjoyable.",
                            ImageUrl = "https://sky-shop.eu/image/cache/may18/icon-student-container-800x800.jpg",
                            IsActive = true,
                            OwnerId = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            Price = 1669.99m,
                            Quantity = 12,
                            Title = "ICON STUDENT CONTAINER",
                            EquipmentCategoryId = 4
                        },
                        new
                        {
                            Id = 7,
                            Title = "COOKIE G35 SKYDIVING HELMET",
                            Brand = "COOKIE COMPOSITES",
                            Quantity = 10,
                            EquipmentCategoryId = 1,
                            Description = "The Cookie G35 Skydiving Helmet improves the G3 with better comfort, customization, and design. It has a traditional shape with a lower back for improved security and ease. The chin is padded for comfort, plus there's more ear space and altimeter pockets. Its visor and new side plates cut noise, and it's ready for FlySight installation. The G35 allows for wide customization with multiple colors for side, top plates, and visors.",
                            OwnerId = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            IsActive = true,
                            Price = 509.99m,
                            ImageUrl = "https://sky-shop.eu/image/cache/catalog/Cookie/G35/Cookie_G35_Skydiving_Helmet_Black-800x800.png"

                        });
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.EquipmentCart", b =>
                {
                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("EquipmentCart");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.EquipmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentsCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Helmets"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Goggles"
                        },
                        new
                        {
                            Id = 3,
                            Name = "JumpSuits"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Containers"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Altimeters"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Parachutes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Other.."
                        });
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsInstructor")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dea12856-c198-4129-b3f3-b893d8395082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c7b2266-b432-4718-bb70-eb88651bcfd0",
                            Email = "instructor@mail.com",
                            EmailConfirmed = false,
                            IsInstructor = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "INSTRUCTOR@MAIL.COM",
                            NormalizedUserName = "INSTRUCTOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEMp4Xxn6p4cUD5PtjNbuRQavOQN37NSuJ2hbzdO7SwxAZFwwB2P+aYUKfDA3CIYkeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "26fba492-97de-4a9a-b18f-47a7d63ef470",
                            TwoFactorEnabled = false,
                            UserName = "instructor"
                        },
                        new
                        {
                            Id = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "74133a53-fceb-4ad7-8e88-e594fcf50e04",
                            Email = "jumper@mail.com",
                            EmailConfirmed = false,
                            IsInstructor = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JUMPER@MAIL.COM",
                            NormalizedUserName = "JUMPER",
                            PasswordHash = "AQAAAAEAACcQAAAAEI+M1NFA9e9jfMMnnOk20qNjlmEC3hhngOp6XYZ2s7caXyFBvZqq/4QCI9PNMm0cYg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8fa709d9-b82f-4d07-ba38-49f8afd10e29",
                            TwoFactorEnabled = false,
                            UserName = "jumper"
                        },
                        new
                        {
                            Id = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1a7845f-2c3a-4bd9-addd-94846181d595",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            IsInstructor = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAENLIdTLriGLtNUe5mvweSqHHq4vPVcBMKc1ssey2nrQPZTqg+gJpgbuarKea3qy1wA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e963ff96-7395-4e28-971c-c46f736e3702",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1e62f853-4a41-4652-b9a9-8e8b236e24c7",
                            ConcurrencyStamp = "1fa54d33-a8ba-47b1-be64-02d6d4836152",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "5d937746-9833-4886-83d1-3c125ad5294c",
                            ConcurrencyStamp = "80196750-3beb-42a1-b321-0aa9c9f41275",
                            Name = "Jumper",
                            NormalizedName = "JUMPER"
                        },
                        new
                        {
                            Id = "c8a8cf93-46b1-4e79-871a-1f4742a0db83",
                            ConcurrencyStamp = "292f8d0e-c368-4cf1-bb0a-b8cda6096ea9",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d6b3ac1f-4fc8-d726-83d9-6d5800ce591e",
                            RoleId = "1e62f853-4a41-4652-b9a9-8e8b236e24c7"
                        },
                        new
                        {
                            UserId = "6d5800ce-d726-4fc8-83d9-d6b3ac1f591e",
                            RoleId = "5d937746-9833-4886-83d1-3c125ad5294c"
                        },
                        new
                        {
                            UserId = "dea12856-c198-4129-b3f3-b893d8395082",
                            RoleId = "c8a8cf93-46b1-4e79-871a-1f4742a0db83"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Cart", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Jump", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.JumpCategory", "Category")
                        .WithMany("Jumps")
                        .HasForeignKey("JumpCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skydiving.Infrastructure.Data.Models.JumpStatus", "JumpStatus")
                        .WithMany("Jumps")
                        .HasForeignKey("JumpStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("JumpStatus");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.JumpOffer", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.Jump", "Jump")
                        .WithMany("JumpsOffers")
                        .HasForeignKey("JumpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skydiving.Infrastructure.Data.Models.Offer", "Offer")
                        .WithMany("JumpsOffers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jump");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Offer", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Equipment", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skydiving.Infrastructure.Data.Models.EquipmentCategory", "Category")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.EquipmentCart", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skydiving.Infrastructure.Data.Models.Equipment", "Equipment")
                        .WithMany("EquipmentsCarts")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Skydiving.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Jump", b =>
                {
                    b.Navigation("JumpsOffers");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.JumpCategory", b =>
                {
                    b.Navigation("Jumps");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.JumpStatus", b =>
                {
                    b.Navigation("Jumps");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Offer", b =>
                {
                    b.Navigation("JumpsOffers");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentsCarts");
                });

            modelBuilder.Entity("Skydiving.Infrastructure.Data.Models.EquipmentCategory", b =>
                {
                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
